"""
Phase 3: Generate REPORT.md from training results.

Reads data/results_all.json + plots/ and writes a comprehensive Markdown report
covering per-ETF performance, baselines, and overfitting diagnostics.

Usage:
    python generate_report.py                # use existing results_all.json
    python generate_report.py --results data/results_all.json
"""
import argparse
import json
from pathlib import Path

import numpy as np
import pandas as pd

HERE = Path(__file__).resolve().parent
DATA_DIR = HERE / "data"
PLOTS_DIR = HERE / "plots"
REPORT_PATH = HERE / "REPORT.md"

ETF_ORDER = ["300ETF", "50ETF", "500ETF", "588000ETF", "159915ETF"]


def load_results(path: Path) -> dict:
    with open(path) as f:
        return json.load(f)


def fmt_pct(v, mul100=True):
    if v is None or (isinstance(v, float) and np.isnan(v)):
        return "N/A"
    return f"{v*100:.4f}%" if mul100 else f"{v:.4f}"


def fmt_ic(v):
    if v is None or (isinstance(v, float) and np.isnan(v)):
        return "N/A"
    return f"{v:+.4f}"


def fmt_sharpe(v):
    if v is None or (isinstance(v, float) and np.isnan(v)):
        return "N/A"
    return f"{v:+.2f}"


def plot_ref(etf: str, name: str) -> str:
    """Return markdown image ref if plot exists, else empty string."""
    p = PLOTS_DIR / f"{name}_{etf}.png"
    if p.exists():
        return f"![{name}_{etf}](plots/{name}_{etf}.png)\n\n"
    return ""


def generate(results: dict) -> str:
    lines = []
    w = lines.append

    w("# Day-Model XGBoost PM Return Predictor — Report\n")
    w("*Generated by `generate_report.py`*\n")

    # ── 1) Executive Summary ──
    w("## 1. Executive Summary\n")
    w("XGBoost regression models predicting PM session return (13:00–15:00) "
      "from early-bar features (first 30 min) + prior-day technical indicators.\n")
    w("**Validation**: Purged walk-forward TimeSeriesSplit (gap=5 days, 5 folds). "
      "Optuna TPE hyperparameter search (60 trials). 20% holdout never used in tuning.\n")

    # Summary table
    w("\n| ETF | Samples | Holdout IC | Holdout Dir | L/S Sharpe | Ridge IC | IS-OOS Gap |")
    w("|-----|---------|-----------|-------------|-----------|----------|------------|")
    for etf in ETF_ORDER:
        r = results.get(etf)
        if not r:
            w(f"| {etf} | — | *not trained* | | | | |")
            continue
        gap_val = r["is_ic"] - r["holdout_ic"]
        ridge_ic = r["baselines"]["ridge"]["ic"]
        w(f"| {etf} | {r['n_samples']} | {fmt_ic(r['holdout_ic'])} "
          f"| {r['holdout_dir_acc']:.3f} "
          f"| {fmt_sharpe(r['holdout_long_short']['ls_sharpe'])} "
          f"| {fmt_ic(ridge_ic)} "
          f"| {gap_val:+.4f} |")
    w("")

    # ── 2) Data & Features ──
    w("## 2. Data & Features\n")
    w("### Feature Groups\n")
    w("| Group | Count | Features |")
    w("|-------|-------|----------|")
    w("| Early-bar (13) | 13 | gap_pct, first_30min_return, early_realized_vol, early_range, "
      "early_volume_ratio, early_trend, early_momentum, gap_direction, "
      "first_bar_return, first_bar_volume, early_vwap_dev, early_skew, early_kurtosis |")
    w("| Day-level (8) | 8 | rsi14, macd_hist, sma20_dist, sma50_dist, "
      "atr14_norm, roc10, bb_pctb, vol20 |")
    w("")
    w("- **Early-bar**: First 6 five-minute bars (9:30–10:00). All computable by 10:00 AM.")
    w("- **Day-level**: Computed on `close_adj` shifted by 1 day (no look-ahead).")
    w("- **Target**: `pm_return` = sum of log returns over bars 24–47 (13:00–15:00 session).")
    w("- **Warmup**: First 60 rows dropped (SMA50/ATR14 burn-in).\n")

    # ── 3) Methodology ──
    w("## 3. Methodology\n")
    w("### Purged Walk-Forward Validation\n")
    w("- **TimeSeriesSplit** (5 folds, expanding window)")
    w("- **Purge gap**: 5 trading days between train and test (no short-term leakage)")
    w("- **Optuna objective**: mean Spearman rank IC across folds")
    w("- **Sampler**: TPE with MedianPruner (n_warmup_steps=10)")
    w("- **n_trials**: 60 (log-scale search over 9 hyperparameters)\n")
    w("### Search Space\n")
    w("| Parameter | Range |")
    w("|-----------|-------|")
    w("| n_estimators | 100–500 (step 50) |")
    w("| max_depth | 3–7 |")
    w("| learning_rate | 0.01–0.1 (log) |")
    w("| subsample | 0.6–1.0 |")
    w("| colsample_bytree | 0.5–1.0 |")
    w("| min_child_weight | 1–10 |")
    w("| gamma | 0.0–2.0 |")
    w("| reg_alpha | 1e-3–1.0 (log) |")
    w("| reg_lambda | 1.0–10.0 (log) |")
    w("")

    # ── 4) Results per ETF ──
    w("## 4. Results\n")
    for etf in ETF_ORDER:
        r = results.get(etf)
        if not r:
            w(f"### {etf}\n\n*Not trained.*\n")
            continue

        w(f"### {etf}\n")
        w(f"- **Samples**: {r['n_samples']} ({r['date_range'][0]} → {r['date_range'][1]})")
        w(f"- **Holdout**: {r['holdout_n']} days ({r['holdout_range'][0]} → {r['holdout_range'][1]})")
        w(f"- **Target stats**: mean={r['target_stats']['mean_pct']:.4f}%, "
          f"std={r['target_stats']['std_pct']:.4f}%, "
          f"Sharpe={r['target_stats']['sharpe_ann']:.2f}\n")

        # Metrics table
        w("#### Metrics\n")
        w("| Metric | XGBoost | Ridge | Zero | Yesterday PM | First 30min Mom |")
        w("|--------|---------|-------|------|--------------|-----------------|")
        bl = r["baselines"]
        w(f"| IC | {fmt_ic(r['holdout_ic'])} | {fmt_ic(bl['ridge']['ic'])} "
          f"| {fmt_ic(bl['zero']['ic'])} | {fmt_ic(bl['yesterday_pm']['ic'])} "
          f"| {fmt_ic(bl['first_30min_mom']['ic'])} |")
        w(f"| Dir Acc | {r['holdout_dir_acc']:.3f} | {bl['ridge']['dir']:.3f} "
          f"| {bl['zero']['dir']:.3f} | {bl['yesterday_pm']['dir']:.3f} "
          f"| {bl['first_30min_mom']['dir']:.3f} |")
        w(f"| RMSE | {r['holdout_rmse']*100:.4f}% | {bl['ridge']['rmse']*100:.4f}% "
          f"| {bl['zero']['rmse']*100:.4f}% | {bl['yesterday_pm']['rmse']*100:.4f}% "
          f"| {bl['first_30min_mom']['rmse']*100:.4f}% |")
        w(f"| L/S Sharpe | {fmt_sharpe(r['holdout_long_short']['ls_sharpe'])} "
          f"| {fmt_sharpe(bl['ridge']['ls_sharpe'])} | — | — | — |")
        w("")

        # Best params
        w("#### Best Hyperparameters\n")
        w("```json")
        w(json.dumps(r["best_params"], indent=2))
        w("```\n")

        # Walk-forward fold ICs
        w("#### Walk-Forward Fold ICs\n")
        w("| Fold | IS IC | OOS IC |")
        w("|------|-------|--------|")
        for i, (is_ic, oos_ic) in enumerate(zip(
            r["walk_forward_is_ic_per_fold"],
            r["walk_forward_oos_ic_per_fold"],
        )):
            w(f"| {i+1} | {is_ic:.4f} | {oos_ic:+.4f} |")
        w(f"| **Overall** | — | {fmt_ic(r['walk_forward_overall_ic'])} |")
        w("")

        # Year-by-year
        if r.get("yearly_ic"):
            w("#### Year-by-Year OOS IC\n")
            w("| Year | IC | Dir Acc | N | L/S Sharpe |")
            w("|------|-----|---------|---|-----------|")
            for yr in sorted(r["yearly_ic"].keys()):
                yi = r["yearly_ic"][yr]
                w(f"| {yr} | {fmt_ic(yi['ic'])} | {yi['dir']:.3f} "
                  f"| {yi['n']} | {fmt_sharpe(yi['ls_sharpe'])} |")
            w("")

        # Plots
        w("#### Diagnostic Plots\n")
        for plot_name in ["holdout_scatter", "ic_timeseries", "feature_importance",
                          "yearly_ic", "purge_sensitivity", "optuna_param_importance"]:
            ref = plot_ref(etf, plot_name)
            if ref:
                w(ref)

    # ── 5) Baseline Comparison ──
    w("## 5. Comparison to Baselines\n")
    w("Four baselines evaluated on the same holdout set:\n")
    w("1. **Zero** (no-skill): Always predicts 0. IC=0 by definition.")
    w("2. **Yesterday PM return**: Autocorrelation baseline. Tests if PM returns are predictable from prior day.")
    w("3. **First 30-min return**: Momentum baseline. Tests AM-to-PM momentum.")
    w("4. **Ridge regression**: Same features, linear model. Isolates XGBoost-specific overfitting.\n")

    w("| ETF | XGB IC > Ridge IC? | XGB IC > Mom IC? | Best Baseline |")
    w("|-----|-------------------|------------------|---------------|")
    for etf in ETF_ORDER:
        r = results.get(etf)
        if not r:
            continue
        bl = r["baselines"]
        xgb_ic = r["holdout_ic"]
        ridge_ic = bl["ridge"]["ic"]
        mom_ic = bl["first_30min_mom"]["ic"]
        best_bl = max(bl.items(), key=lambda x: x[1].get("ic", 0))
        w(f"| {etf} | {'Yes' if xgb_ic > ridge_ic else 'No'} "
          f"| {'Yes' if xgb_ic > mom_ic else 'No'} "
          f"| {best_bl[0]} (IC={fmt_ic(best_bl[1].get('ic', 0))}) |")
    w("")

    # ── 6) Overfitting Risk ──
    w("## 6. Risk of Overfitting\n")

    w("### 6.1 IS vs OOS Gap\n")
    w("| ETF | IS IC | OOS IC | Gap | Assessment |")
    w("|-----|-------|--------|-----|-----------|")
    for etf in ETF_ORDER:
        r = results.get(etf)
        if not r:
            continue
        gap_val = r["is_ic"] - r["holdout_ic"]
        severity = "Low" if gap_val < 0.3 else ("Moderate" if gap_val < 0.5 else "High")
        w(f"| {etf} | {r['is_ic']:.4f} | {r['holdout_ic']:.4f} | {gap_val:+.4f} | {severity} |")
    w("")

    w("### 6.2 Regime Breakdown (Year-by-Year)\n")
    w("See per-ETF year-by-year tables in §4. Large year-to-year IC variance signals regime sensitivity.\n")

    w("### 6.3 Purge-Gap Sensitivity\n")
    w("If IC drops sharply as purge gap increases from 0→5→10, it indicates short-term leakage.\n")
    w("| ETF | Gap=0 | Gap=5 | Gap=10 | Delta(0→10) |")
    w("|-----|-------|-------|--------|------------|")
    for etf in ETF_ORDER:
        r = results.get(etf)
        if not r:
            continue
        ps = r["purge_sensitivity"]
        g0 = ps.get("0", {}).get("mean_ic", 0)
        g5 = ps.get("5", {}).get("mean_ic", 0)
        g10 = ps.get("10", {}).get("mean_ic", 0)
        delta = g0 - g10
        w(f"| {etf} | {g0:+.4f} | {g5:+.4f} | {g10:+.4f} | {delta:+.4f} |")
    w("")

    w("### 6.4 Feature Importance Stability\n")
    w("Compare gain importance (IS-biased) vs permutation importance (OOS) across features. "
      "Large divergence indicates overfitting to specific features.\n")

    w("### 6.5 Top-5 Features: Gain vs Permutation\n")
    for etf in ETF_ORDER:
        r = results.get(etf)
        if not r:
            continue
        gi = pd.Series(r["gain_importance"]).sort_values(ascending=False).head(5)
        pi = pd.Series(r["permutation_importance"]).sort_values(ascending=False).head(5)
        w(f"\n**{etf}**:\n")
        w("| Rank | Gain Importance | Permutation Importance |")
        w("|------|----------------|----------------------|")
        for rank, ((gf, gv), (pf, pv)) in enumerate(zip(gi.items(), pi.items()), 1):
            w(f"| {rank} | {gf} ({gv:.4f}) | {pf} ({pv:+.6f}) |")
    w("")

    w("### 6.6 Hyperparameter Sensitivity\n")
    w("Optuna parameter importance shows which hyperparameters most affect CV IC. "
      "If one parameter dominates (>50%), the model is sensitive to that choice.\n")
    for etf in ETF_ORDER:
        r = results.get(etf)
        if not r or not r.get("optuna_param_importance"):
            continue
        opi = r["optuna_param_importance"]
        top_param = max(opi, key=opi.get)
        w(f"- **{etf}**: Most influential = `{top_param}` ({opi[top_param]:.2%})")
    w("")

    # ── 7) Conclusions ──
    w("## 7. Conclusions & Caveats\n")

    # Auto-generate conclusions based on results
    deployable = []
    marginal = []
    weak = []
    for etf in ETF_ORDER:
        r = results.get(etf)
        if not r:
            continue
        ic = r["holdout_ic"]
        ls = r["holdout_long_short"]["ls_sharpe"]
        ridge_ic = r["baselines"]["ridge"]["ic"]
        if ic > 0.03 and ls > 0.5 and ic > ridge_ic:
            deployable.append(etf)
        elif ic > 0 and ls > 0:
            marginal.append(etf)
        else:
            weak.append(etf)

    if deployable:
        w(f"**Potentially deployable** (IC>0.03, L/S Sharpe>0.5, beats Ridge): "
          f"{', '.join(deployable)}\n")
    if marginal:
        w(f"**Marginal** (positive IC but weak Sharpe or below Ridge): "
          f"{', '.join(marginal)}\n")
    if weak:
        w(f"**Weak/Not recommended** (negative IC or no edge): "
          f"{', '.join(weak)}\n")

    w("\n**Key caveats**:\n")
    w("1. PM return prediction is inherently noisy (low signal-to-noise ratio)")
    w("2. IS IC >> OOS IC gap is expected for tree models on financial data")
    w("3. Purge-gap sensitivity should be checked: large gap=0 vs gap=5 delta = leakage risk")
    w("4. Ridge baseline often competitive — XGBoost must justify its complexity")
    w("5. Year-by-year stability is critical: models trained on bull regimes fail in crashes")
    w("6. Transaction costs not modeled — even positive IC may not survive slippage")
    w("")

    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--results", default=str(DATA_DIR / "results_all.json"))
    args = ap.parse_args()

    path = Path(args.results)
    if not path.exists():
        print(f"ERROR: {path} not found. Run train_model.py first.")
        return

    results = load_results(path)
    md = generate(results)

    REPORT_PATH.write_text(md, encoding="utf-8")
    print(f"Report written → {REPORT_PATH} ({len(md)} chars, {len(md.splitlines())} lines)")

    # Print ETF summary
    for etf in ETF_ORDER:
        r = results.get(etf)
        if r:
            print(f"  {etf}: IC={r['holdout_ic']:+.4f}  "
                  f"Dir={r['holdout_dir_acc']:.3f}  "
                  f"L/S={r['holdout_long_short']['ls_sharpe']:+.2f}")


if __name__ == "__main__":
    main()
